import type { AnchorCollection, AnchorRule } from '../types/config';

type Kind = 'substring' | 'regex' | 'glob';

const resolveKind = (pattern: string, rule: AnchorRule): Kind => {
  if (rule.match) return rule.match;
  if (pattern.startsWith('regex:') || (pattern.length > 2 && pattern.startsWith('/') && pattern.endsWith('/'))) {
    return 'regex';
  }
  if (pattern.includes('*') || pattern.includes('?')) return 'glob';
  return 'substring';
};

const isPath = (rule: AnchorRule): boolean =>
  rule.target === 'path' || rule.target === 'any' || rule.target == null;

// Cedar `like` treats `*` as a wildcard; escape literal `\`, `"`, and `*`.
const cedarLike = (pattern: string): string =>
  pattern.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\*/g, '\\*');

/**
 * Compile NBCLI anchors into Cedar `forbid` policies. HONEST LIMITATIONS: Cedar has
 * no content/substring-on-content, no regex, no glob, and no case-insensitive `like`,
 * so this covers **path substring** anchors only via `resource.path like "*…*"`
 * (case-sensitive); everything else is emitted as a skip comment. Use the Rego export
 * for full, matcher-faithful coverage.
 */
export function toCedar(anchors: AnchorCollection): string {
  const lines: string[] = [
    '// Generated by NBCLI (`nsb policy export --format cedar`). Do not edit by hand.',
    '// LIMITATION: Cedar covers PATH substring anchors only (no content/regex/glob, case-sensitive).',
    '// Use the Rego export (`--format rego`) for full, matcher-faithful coverage.',
    '',
  ];

  for (const [category, rules] of Object.entries(anchors)) {
    for (const rule of rules) {
      if (!rule.enforce) continue;
      for (const pattern of rule.patterns) {
        const kind = resolveKind(pattern, rule);
        if (kind !== 'substring') {
          lines.push(`// skipped ${rule.id} (${kind} not supported in Cedar): ${pattern}`);
          continue;
        }
        if (!isPath(rule)) {
          lines.push(`// skipped ${rule.id} (content anchor; Cedar is path-only): ${pattern}`);
          continue;
        }
        lines.push(`// ${rule.id} [${category}] — ${rule.reason}`);
        lines.push('forbid (principal, action, resource)');
        lines.push(`when { resource.path like "*${cedarLike(pattern)}*" };`);
        lines.push('');
      }
    }
  }

  return `${lines.join('\n')}\n`;
}
