import type { AnchorCollection, AnchorRule } from '../types/config';

type Field = 'path' | 'content';
type Kind = 'substring' | 'regex' | 'glob';

const fieldsFor = (rule: AnchorRule): Field[] =>
  rule.target === 'path' ? ['path'] : rule.target === 'content' ? ['content'] : ['path', 'content'];

// Mirror the matcher's resolveMatchType: explicit `match` wins; else auto-detect.
const resolveKind = (pattern: string, rule: AnchorRule): Kind => {
  if (rule.match) return rule.match;
  if (pattern.startsWith('regex:') || (pattern.length > 2 && pattern.startsWith('/') && pattern.endsWith('/'))) {
    return 'regex';
  }
  if (pattern.includes('*') || pattern.includes('?')) return 'glob';
  return 'substring';
};

const regexBody = (pattern: string): string => {
  if (pattern.startsWith('regex:')) return pattern.slice(6);
  if (pattern.length > 2 && pattern.startsWith('/') && pattern.endsWith('/')) return pattern.slice(1, -1);
  return pattern;
};

// Escape any string for a double-quoted Rego string literal (handles backtick/quote/newlines safely).
const rs = (s: string): string =>
  `"${s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')}"`;

// Mirror the matcher's globToRegex: anchored, glob * -> .* and ? -> .
const globToRegex = (glob: string): string =>
  `^${glob.replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*').replace(/\?/g, '.')}$`;

// Build a CASE-INSENSITIVE condition mirroring the matcher (lowercases + 'i' flag).
const condition = (pattern: string, field: Field, rule: AnchorRule): string => {
  const kind = resolveKind(pattern, rule);
  if (kind === 'regex') return `regex.match(${rs(`(?i)${regexBody(pattern)}`)}, input.${field})`;
  if (kind === 'glob') return `regex.match(${rs(`(?i)${globToRegex(pattern)}`)}, input.${field})`;
  return `contains(lower(input.${field}), ${rs(pattern.toLowerCase())})`;
};

/**
 * Compile NBCLI anchors into an OPA/Rego policy that is FAITHFUL to the matcher
 * (case-insensitive; substring/regex/glob). Enforced anchors become `deny` rules
 * (a match => not allowed); advisory anchors become `warn` rules. Validate with `opa check`.
 */
export function toRego(anchors: AnchorCollection): string {
  const deny: string[] = [];
  const warn: string[] = [];

  for (const [category, rules] of Object.entries(anchors)) {
    for (const rule of rules) {
      for (const pattern of rule.patterns) {
        for (const field of fieldsFor(rule)) {
          const set = rule.enforce ? deny : warn;
          const name = rule.enforce ? 'deny' : 'warn';
          set.push(
            `# ${rule.id} [${category}]${rule.enforce ? ' (enforced)' : ' (advisory)'}\n` +
              `${name} contains msg if {\n  ${condition(pattern, field, rule)}\n  msg := ${rs(`${rule.id}: ${rule.reason}`)}\n}`,
          );
        }
      }
    }
  }

  return (
    [
      '# Generated by NBCLI (`nsb policy export --format rego`). Do not edit by hand.',
      '# input: { "path": "<file path>", "content": "<file content>" }',
      'package nbcli.governance',
      '',
      'import future.keywords.if',
      'import future.keywords.contains',
      '',
      'default allow := true',
      '',
      'allow := false if { count(deny) > 0 }',
      '',
      '# Seed rules so `deny`/`warn` are always defined sets (count() stays safe with no anchors).',
      'deny contains msg if { false; msg := "" }',
      'warn contains msg if { false; msg := "" }',
      '',
      '# --- enforced (block) rules ---',
      ...deny,
      '',
      '# --- advisory (warn) rules ---',
      ...warn,
    ].join('\n') + '\n'
  );
}
